name: Build Windows

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      WIN_TARGET: "x86_64-pc-windows-gnu"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows Rust target
        run: rustup target add $env:WIN_TARGET

      - name: Build release binary
        run: cargo build --release --target $env:WIN_TARGET

      - name: Copy EXE into installer directory
        run: Copy-Item "target/$env:WIN_TARGET/release/gem-player.exe" -Destination "installer/gem-player.exe" -Force

      - name: Debug paths
        run: |
          echo "Workspace: ${{ github.workspace }}"
          dir ${{ github.workspace }}\installer

      - name: Compile Inno Setup Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer/installer.iss
          options: /O+

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-installer
          path: installer/Output/GemPlayerInstaller.exe
