name: Build macOS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      APP_NAME: "Gem Player"
      APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
      APPLE_SIGNING_ID: ${{ secrets.APPLE_SIGNING_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release app bundle
        run: cargo bundle --release

      - name: Codesign app bundle
        run: |
          codesign --force --deep --options runtime \
            --sign "$APPLE_SIGNING_IDENTITY" \
            "target/release/bundle/osx/$APP_NAME.app"
            
      - name: Create DMG
        run: |
          create-dmg \
            --volname "$APP_NAME Installer" \
            --app-drop-link 0 0 \
            --codesign "$APPLE_SIGNING_IDENTITY" \
            "target/release/bundle/osx/$APP_NAME.dmg" \
            "target/release/bundle/osx/$APP_NAME.app"

      - name: Write Apple API key file
        run: echo "$APPLE_API_KEY" > AuthKey.p8

      - name: Notarize app
        run: |
          xcrun notarytool submit "target/release/bundle/osx/$APP_NAME.dmg" \
            --key AuthKey.p8 \
            --key-id "$APPLE_API_KEY_ID" \
            --issuer "$APPLE_API_ISSUER_ID" \
            --wait

      - name: Staple notarization
        run: |
          xcrun stapler staple "target/release/bundle/osx/$APP_NAME.app"
          xcrun stapler staple "target/release/bundle/osx/$APP_NAME.dmg"

      - name: Verify
        run: spctl --assess --type execute --verbose "target/release/bundle/osx/$APP_NAME.app"
