name: Build Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APP_NAME: "Gem Player"
      WIN_TARGET: "x86_64-pc-windows-gnu"
      WIN_EXE_NAME: "Gem Player.exe"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows Rust target
        run: rustup target add $env:WIN_TARGET

      - name: Build release binary
        run: cargo build --release --target $env:WIN_TARGET

      - name: Rename EXE to friendly name
        run: |
          $targetDir = "target/$env:WIN_TARGET/release"
          $exeFile = Get-ChildItem $targetDir -Filter "*.exe" | Where-Object { $_.Name -like "gem_player*.exe" } | Select-Object -First 1
          $dest = Join-Path $targetDir $env:WIN_EXE_NAME
          Copy-Item -Path $exeFile.FullName -Destination $dest -Force

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Build MSI
        run: |
          # Compile WiX installer
          candle.exe installer.wxs -o installer.wixobj
          # Link MSI
          light.exe installer.wixobj -o target/release/GemPlayerInstaller.msi

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-msi
          path: target/release/GemPlayerInstaller.msi
