name: Build Windows

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      WIN_TARGET: "x86_64-pc-windows-gnu"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows Rust target
        run: rustup target add $env:WIN_TARGET

      - name: Build release binary
        run: cargo build --release --target $env:WIN_TARGET

      - name: Copy EXE for installer
        run: Copy-Item "target/$env:WIN_TARGET/release/gem-player.exe" -Destination "installer/Gem Player.exe" -Force

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build MSI
        run: dotnet build installer/installer.wixproj -c Release

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-msi
          path: installer/bin/Release/*.msi
