name: Build Windows

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APP_NAME: "Gem Player"
      WIN_TARGET: "x86_64-pc-windows-gnu"
      WIN_EXE_NAME: "Gem Player.exe"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows Rust target
        run: rustup target add $env:WIN_TARGET

      - name: Build release binary
        run: cargo build --release --target $env:WIN_TARGET

      - name: Rename EXE to friendly name
        run: |
          $targetDir = "target/$env:WIN_TARGET/release"
          $exeFile = Join-Path $targetDir "gem-player.exe"
          $dest = Join-Path $targetDir $env:WIN_EXE_NAME
          Copy-Item -Path $exeFile -Destination $dest -Force

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build MSI
        run: dotnet build installer/installer.wixproj -c Release

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-msi
          path: target/release/GemPlayerInstaller.msi
