name: Build Windows

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      WIN_TARGET: "x86_64-pc-windows-gnu"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows Rust target
        run: rustup target add $env:WIN_TARGET

      # TODO: Change back to release build when ready
      - name: Build debug binary
        run: cargo build --target $env:WIN_TARGET 

      - name: Copy EXE into root
        run: Copy-Item "target/$env:WIN_TARGET/debug/gem-player.exe" -Destination "gem-player.exe" -Force

      - name: List current directory
        run: dir

      # - name: Compile .ISS to .EXE Installer
      #   uses: Minionguyjpro/Inno-Setup-Action@v1.2.1
      #   with:
      #     path: setup.iss
      #     options: /O+

      - name: compile iss  
        uses: zhuzichu520/inno-setup-action@v1.0.1
        with: 
            filepath: 'setup.iss'

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-installer
          path: GemPlayerInstaller.exe
