name: Build Windows

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  WIN_TARGET: x86_64-pc-windows-gnu

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows Rust target
        run: rustup target add $env:WIN_TARGET

      - name: Build release binary
        run: cargo build --release --target $env:WIN_TARGET

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Compile installer
        run: iscc windows_installer.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-installer
          path: target/${{ env.WIN_TARGET }}/release/GemPlayerInstaller.exe