name: Build Windows

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Metadata
        id: metadata
        uses: nicolaiunrein/cargo-get@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Install Inno Setup
        run: choco install innosetup --yes
      
      - name: Prepare installer folder
        run: mkdir -p target/release/installer

      - name: Run Inno Setup Compiler
        run: >
          iscc "windows_installer.iss" 
          /DAppVersion=${{ steps.metadata.outputs.package_version }} 
          /DExePath="target/release/${{ steps.metadata.outputs.package_name }}.exe"
          /O"target/release/installer" `
          /F"GemPlayer-${{ steps.metadata.outputs.package_version }}-windows-x64"

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-${{ steps.metadata.outputs.package_version }}
          path: target/release/installer/GemPlayer-${{ steps.metadata.outputs.package_version }}-windows-x64.exe
