name: Build Windows

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  WIN_TARGET: x86_64-pc-windows-gnu

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Cargo package info
        id: info
        uses: rabbitson87/get-cargo-package-info@v1
        with:
          file_name: Cargo.toml
          package: |
            name
            version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows Rust target
        run: rustup target add $env:WIN_TARGET

      - name: Build release binary
        run: cargo build --release --target $env:WIN_TARGET

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Run Inno Setup Compiler
        run: |
          cd target/$env:WIN_TARGET/release/installer
          iscc windows_installer.iss

      - name: Rename installer with version
        run: |
          $version = "${{ fromJson(steps.info.outputs.object).package.version }}"
          Rename-Item `
            -Path "target\$env:WIN_TARGET\release\installer\GemPlayerInstaller.exe" `
            -NewName "GemPlayerInstaller-v$version.exe"

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: GemPlayer-windows-installer-v${{ fromJson(steps.info.outputs.object).package.version }}
          path: target/${{ env.WIN_TARGET }}/release/installer/GemPlayerInstaller-v${{ fromJson(steps.info.outputs.object).package.version }}.exe
