name: Build macOS

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      APP_NAME: "Gem Player"   # Human-friendly app name
      BUILD_NAME: "gem_player" # File-safe build name

    steps:
      - uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        id: version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -1 | sed -E 's/version\s*=\s*"([^"]+)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-bundle and create-dmg
        run: |
          cargo install cargo-bundle
          brew install create-dmg

      - name: Build release app bundle
        run: cargo bundle --release

      - name: Import Code Signing Certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}

      - name: Codesign app bundle
        run: |
          codesign --force --deep --options runtime \
            --sign "${{ secrets.APPLE_SIGNING_ID }}" \
            "target/release/bundle/osx/$APP_NAME.app"

      - name: Create DMG
        run: |
          create-dmg \
            --volname "$APP_NAME Installer" \
            --app-drop-link 0 0 \
            --codesign "${{ secrets.APPLE_SIGNING_ID }}" \
            "target/release/bundle/osx/$BUILD_NAME.dmg" \
            "target/release/bundle/osx/$APP_NAME.app"

          # Rename DMG to include version and platform
          mv "target/release/bundle/osx/$BUILD_NAME.dmg" \
             "target/release/bundle/osx/${BUILD_NAME}_${VERSION}_macos.dmg"

      - name: Decode App Store Connect API key
        run: |
          printf "%s" "${{ secrets.APPLE_API_KEY_FILE_BASE64 }}" | base64 --decode > AuthKey.p8

      - name: Notarize app
        run: |
          xcrun notarytool submit "target/release/bundle/osx/${BUILD_NAME}_${VERSION}_macos.dmg" \
            --issuer "${{ secrets.APPLE_API_ISSUER_ID }}" \
            --key-id "${{ secrets.APPLE_API_KEY_ID }}" \
            --key AuthKey.p8 \
            --wait

      - name: Staple notarization
        run: |
          xcrun stapler staple "target/release/bundle/osx/$APP_NAME.app"
          xcrun stapler staple "target/release/bundle/osx/${BUILD_NAME}_${VERSION}_macos.dmg"

      - name: Verify
        run: spctl --assess --type execute --verbose "target/release/bundle/osx/$APP_NAME.app"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${BUILD_NAME}_${VERSION}_macos"
          path: "target/release/bundle/osx/${BUILD_NAME}_${VERSION}_macos.dmg"